version: 2
enable-beta-ecosystems: true
updates:
  - directory: /
    open-pull-requests-limit: 2
    package-ecosystem: "pub"
    rebase-strategy: auto
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Tokyo
  - directory: /android
    package-ecosystem: "gradle"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Tokyo