version: 2
enable-beta-ecosystems: true
updates:
  - directory: /
    open-pull-requests-limit: 2
    package-ecosystem: "pub"
    rebase-strategy: auto
    schedule:
      interval: weekly
      time: "08:30"
      timezone: "Aisa/Tokyo"
  - directory: /android
    open-pull-requests-limit: 2
    package-ecosystem: "gradle"
    schedule:
      interval: weekly
      time: "08:30"
      timezone: "Aisa/Tokyo"