name: petmily
description: 우리가 만들어가는 반려동물 캔버스
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.2
  go_router: ^6.5.3
<<<<<<< HEAD
  provider: ^6.0.1
  firebase_auth: ^4.4.0
  http: ^0.13.6
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  logger: ^1.3.0

=======
  provider: ^6.0.5
  kakao_flutter_sdk: ^1.4.2
  dio: ^4.0.6
  shared_preferences: ^2.1.1
  http: ^0.13.6
>>>>>>> 42ee48c7a00cdff834a2ab77bd15da578688c356

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kakao_login_large_narrow.png

  # Variable 폰트를 사용합니다.
  fonts:
    - family: "PretendardVariation"
      fonts:
        - asset: assets/font/PretendardVariable.ttf

  assets:
  - assets/images/
