name: petmily
description: 우리가 만들어가는 반려동물 캔버스
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.2
  go_router: ^6.5.3
  provider: ^6.0.1
  firebase_auth: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Variable 폰트를 사용합니다.
  fonts:
    - family: "PretendardVariation"
      fonts:
        - asset: assets/font/PretendardVariable.ttf

  assets:
  - assets/images/ic_google.png
  - assets/images/ic_kakao.png
  - assets/images/ic_naver.png
