name: petmily
description: 우리가 만들어가는 반려동물 캔버스
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.2
  go_router: ^6.5.3
  dio: ^5.2.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  http: ^0.13.6
  image_picker: ^0.8.8
  multiple_images_picker: ^1.0.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.2
  path_provider: ^2.0.15
  kakao_flutter_sdk: ^1.4.3
  animated_text_kit: ^4.2.2
  lottie: ^2.4.0
  transition: ^2.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Variable 폰트를 사용합니다.
  fonts:
    - family: "PretendardVariation"
      fonts:
        - asset: assets/font/PretendardVariable.ttf

